

# 134E Apstar 6C

[11473-V-32755]
    DELIVERY_SYSTEM = DVBS2
    FREQUENCY       = 11473000
    SYMBOL_RATE     = 32755000
    POLARIZATION    = VERTICAL

[11507-V-12857]
    DELIVERY_SYSTEM = DVBS2
    FREQUENCY       = 11507000
    SYMBOL_RATE     = 12857000
    POLARIZATION    = VERTICAL

[11540-V-44991]
    DELIVERY_SYSTEM = DVBS2
    FREQUENCY       = 11540000
    SYMBOL_RATE     = 44991000
    POLARIZATION    = VERTICAL

[11603-V-40944]
    DELIVERY_SYSTEM = DVBS2
    FREQUENCY       = 11603000
    SYMBOL_RATE     = 40944000
    POLARIZATION    = VERTICAL

[11665-V-44991]
    DELIVERY_SYSTEM = DVBS2
    FREQUENCY       = 11665000
    SYMBOL_RATE     = 44991000
    POLARIZATION    = VERTICAL

[12410-V-50465]
    DELIVERY_SYSTEM = DVBS2
    FREQUENCY       = 12410000
    SYMBOL_RATE     = 50465000
    POLARIZATION    = VERTICAL

[12522-V-26280]
    DELIVERY_SYSTEM = DVBS2
    FREQUENCY       = 12522000
    SYMBOL_RATE     = 26280000
    POLARIZATION    = VERTICAL

[12592-V-44991]
    DELIVERY_SYSTEM = DVBS2
    FREQUENCY       = 12592000
    SYMBOL_RATE     = 44991000
    POLARIZATION    = VERTICAL

